services:
  twitter-ero-video-ranking-downloader:
    image: hexbkyoma/twitter-ero-video-ranking-downloader:latest
    container_name: twitter-ero-video-ranking-downloader
    restart: unless-stopped
    ports:
      - "2617:2617"
    volumes:
      - ./config.json:/app/config.json
      - /vol1/1000/AdultMedia/tw:/data/downloads
    environment:
      - TZ=Asia/Shanghai
