services:
  twitter-ero-video-ranking-downloader:
    build: .
    container_name: twitter-ero-video-ranking-downloader
    restart: unless-stopped
    ports:
      - "2617:2617"
    volumes:
      - /vol1/1000/AdultMedia/tw:/data/downloads
      - ./config.json:/app/config.json
    environment:
      - TZ=Asia/Shanghai
